import os

JWT_SECRET_KEY = os.getenv('JWT_SECRET_KEY', "")
AUTH_TOKEN_TIMEDELTA = os.getenv('AUTH_TOKEN_TIMEDELTA', 60)
REFRESH_TOKEN_TIMEDELTA = os.getenv('REFRESH_TOKEN_TIMEDELTA', 60 * 24)

REMEMBER_ME_MUL_AUTH = 24 * AUTH_TOKEN_TIMEDELTA
REMEMBER_ME_MUL_REFRESH = 7 * REFRESH_TOKEN_TIMEDELTA
